### ISSUE TITLE
Scheduled maintenance `NCS Integration`'s Database server

### ISSUE THREAD

**Issue by socheatsok78** [soramitsukhmer/upptime#7]
There are some issues regarding to `NCS Integration`'s Database server

```
<!--
start: 2021-05-28T15:00:00.220Z
end: 2021-05-28T17:00:00.220Z
expectedDown: ncs-integration
-->
```

**Comment by socheatsok78** [comment]
There are some issues due to `ncs-change-management` database!

Tested the following sql statement and currently wait for result!

```sql
GRANT UNLIMITED TABLESPACE TO CHANGE_MANAGEMENT_I
```

ref: https://support.esri.com/en/technical-article/000013877

**Comment by socheatsok78** [comment]
Another issues has occurred for `ncs-system-setting`

```log
ncs-system-setting_1       | 2021-05-28 16:55:49.387  INFO [system-setting,,,] 23 --- [           main] liquibase.executor.jvm.JdbcExecutor      : CREATE SEQUENCE SYSTEM_SETTING_I.SEQ_ACCOUNT_CLASS START WITH 10 INCREMENT BY 50
ncs-system-setting_1       | 2021-05-28 16:55:49.390 ERROR [system-setting,,,] 23 --- [           main] liquibase.changelog.ChangeSet            : Change Set db/changelog/20201024153420_sequences_changelog.xml::create-sequences-for-each-table::sovannarith failed.  Error: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |  [Failed SQL: (955) CREATE SEQUENCE SYSTEM_SETTING_I.SEQ_ACCOUNT_CLASS START WITH 10 INCREMENT BY 50]
ncs-system-setting_1       | 2021-05-28 16:55:49.392  WARN [system-setting,,,] 23 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/20201024153420_sequences_changelog.xml::create-sequences-for-each-table::sovannarith:
ncs-system-setting_1       |      Reason: liquibase.exception.DatabaseException: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |  [Failed SQL: (955) CREATE SEQUENCE SYSTEM_SETTING_I.SEQ_ACCOUNT_CLASS START WITH 10 INCREMENT BY 50]
ncs-system-setting_1       | 2021-05-28 16:55:49.411  INFO [system-setting,,,] 23 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
ncs-system-setting_1       | 2021-05-28 16:55:49.442  INFO [system-setting,,,] 23 --- [           main] ConditionEvaluationReportLoggingListener :
ncs-system-setting_1       |
ncs-system-setting_1       | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ncs-system-setting_1       | 2021-05-28 16:55:49.454 ERROR [system-setting,,,] 23 --- [           main] o.s.boot.SpringApplication               : Application run failed
ncs-system-setting_1       |
ncs-system-setting_1       | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/20201024153420_sequences_changelog.xml::create-sequences-for-each-table::sovannarith:
ncs-system-setting_1       |      Reason: liquibase.exception.DatabaseException: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |  [Failed SQL: (955) CREATE SEQUENCE SYSTEM_SETTING_I.SEQ_ACCOUNT_CLASS START WITH 10 INCREMENT BY 50]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at kh.org.ncs.system_setting.SystemSettingServiceApplicationKt.main(SystemSettingServiceApplication.kt:23) [classes!/:na]
ncs-system-setting_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
ncs-system-setting_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
ncs-system-setting_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
ncs-system-setting_1       | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
ncs-system-setting_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
ncs-system-setting_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
ncs-system-setting_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [app.jar:na]
ncs-system-setting_1       | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [app.jar:na]
ncs-system-setting_1       | Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/20201024153420_sequences_changelog.xml::create-sequences-for-each-table::sovannarith:
ncs-system-setting_1       |      Reason: liquibase.exception.DatabaseException: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |  [Failed SQL: (955) CREATE SEQUENCE SYSTEM_SETTING_I.SEQ_ACCOUNT_CLASS START WITH 10 INCREMENT BY 50]
ncs-system-setting_1       | 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46) ~[spring-boot-autoconfigure-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
ncs-system-setting_1       | 	... 26 common frames omitted
ncs-system-setting_1       | Caused by: liquibase.exception.DatabaseException: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |  [Failed SQL: (955) CREATE SEQUENCE SYSTEM_SETTING_I.SEQ_ACCOUNT_CLASS START WITH 10 INCREMENT BY 50]
ncs-system-setting_1       | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1276) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1258) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	... 35 common frames omitted
ncs-system-setting_1       | Caused by: java.sql.SQLSyntaxErrorException: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.2.jar!/:na]
ncs-system-setting_1       | 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.2.jar!/:na]
ncs-system-setting_1       | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398) ~[liquibase-core-3.8.6.jar!/:na]
ncs-system-setting_1       | 	... 40 common frames omitted
ncs-system-setting_1       | Caused by: oracle.jdbc.OracleDatabaseException: ORA-00955: name is already used by an existing object
ncs-system-setting_1       |
ncs-system-setting_1       | 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513) ~[ojdbc8-19.3.0.0.jar!/:19.3.0.0.0]
ncs-system-setting_1       | 	... 55 common frames omitted
ncs-system-setting_1       |
```

**Comment by socheatsok78** [comment]
Issues with `ncs-change-management` service has been resolved!

**Comment by soksanchhom** [comment]
cc @jacky2020hor

**Comment by phuylai-oeung** [comment]
well received......thanks everyone... <3
